### ISSUE TITLE
data set

### ISSUE THREAD

**Issue by garikhgh** [jrieke/shape-detection#4]
Hi, nice work. came across while looking for such approach.
one question, on what kind of images you have trained your model, that is, you have only small images of that figures or the figures are on entire images? give some hints.

**Comment by jrieke** [comment]
Thanks! Each subplot of the image in the README is one "image" (I use numpy arrays internally) that I train on. Read more [here](https://towardsdatascience.com/object-detection-with-neural-networks-a4e2c46b4491).
